thoughtbot/factory_bot_rails

.travis.yml

`factory_bot` [dropped `jruby-19`](https://github.com/thoughtbot/factory_bot/commit/9f1b32e07100d9a7da5439532b14cb7c349a2563#diff-354f30a63fb0907d4ad57269548329e3) from the testing matrix almost a year ago and the `factory_bot_rails` build has been [broken for some time](https://travis-ci.org/thoughtbot/factory_bot_rails/builds) (~ 3 years).
Also makes the Rails `4.1` appraisal with Ruby 2.4 / 2.5 an 'allowed failure' because some tests fail with ActiveSupport `4.1` (this fix doesn't appear to have been backdated):
https://github.com/rails/rails/pull/25161
https://github.com/rails/rails/pull/25737
Planning to add Rails `5.1` and `5.2` appraisals in a subsequent PR.

Drop jruby & add modern Rubies to Travis config

---

factory_bot_rails.gemspec

This reduces unneeded redirection from `http://...` to `https://...` when someone visits this gem's homepage via https://rubygems.org/gems/factory_bot_rails

GitHub is HTTPS by default

---

.travis.yml
Appraisals
features/load_definitions.feature
gemfiles/rails5.1.gemfile
gemfiles/rails5.2.gemfile

- Add Rails 5.1 and 5.2 to Appraisal
- Avoid running combinations we know are going to fail by moving to
"exclude" instead of "allow_failures"

Test against Rails 5.1 and 5.2

---

README.md

First of all, thanks for factory_bot! I use it everywhere and my tests are way cleaner for it.
Would you be up for adding a badge showing how stable / bug-free new releases are? I realised we've got the data to show that at Dependabot, so I threw together the below:
[![Gem Version](https://badge.fury.io/rb/factory_bot_rails.svg)](http://badge.fury.io/rb/factory_bot_rails) [![SemVer](https://api.dependabot.com/badges/compatibility_score?dependency-name=factory_bot_rails&package-manager=bundler&version-scheme=semver)](https://dependabot.com/compatibility-score.html?dependency-name=factory_bot_rails&package-manager=bundler&version-scheme=semver)
The gem version badge is totally standard. The semver stability one is based on all of the updates Dependabot has done for factory_bot users - if …

Add version and SemVer stability badges to README

---

.travis.yml

Rails 4.1 does not work with Ruby 2.4 or higher, so no need to run a
combination we know will fail.

Don't run Rails 4.1 with Ruby head on travis

---

Gemfile.lock
lib/factory_bot_rails/generator.rb
lib/generators/factory_bot/model/model_generator.rb

Configuration#generators was deprecated in favor of
Configuration#app_generators back in Rails 3.1 (https://github.com/rails/rails/commit/04cbabb0a0206553d7b474ee7a191d19957048fe).
Since we started work on factory_bot_rails 5, which only supports Rails
4.2+, we no longer need the conditional.
I also updated the development Gemfile, since it was out of date,
and replaced a nested if/else with elsif.

Remove unneeded conditional for app_generators

---

README.md
features/load_definitions.feature
lib/factory_bot_rails/railtie.rb

Currently the only way to customize the factory definition file
paths is to do it in an initializer right after the
"factory_bot.set_factory_paths" initializer. With this PR,
we can customize factory definition file paths by
setting `config.factory_bot.definition_file_paths`
in config/application.rb or the appropriate environment file.
We should be able to close #149 and #180 as well, since using this
configuration can replace the initializer solution for sharing factories
in an engine (the initializer solution will still work, but with the new
configuration you don't need to know anything about the
fbr railtie).
This will also allow us to close #192, since we can use this
configuration with an empty array to disable automatic loading
of factories in development.
I added documentation for …

 Introduce definition file path configuration

---

README.md

Unclosed String literal in README

---

.rubocop.yml
Appraisals
Rakefile

This partially addresses [#239](https://github.com/thoughtbot/factory_bot_rails/issues/293) by deleting references to Rakefile and the Appraisals file from `.rubocop.yml` and fixing the subsequent warnings.

Address todos generated by rubocop for files in Rakefile and Appraisals.

---

.rubocop.yml
lib/generators/factory_bot.rb
lib/generators/factory_bot/model/model_generator.rb

This partially addresses [#239](https://github.com/thoughtbot/factory_bot_rails/issues/293) by deleting references to files in the `lib/generators` directory from `.rubocop.yml` and fixing the subsequent warnings.
One caveat: I did not address the `Naming/MemoizedInstanceVariableName` cop for lib/generators/factory_bot.rb in favor of honoring “Use a leading underscore when defining instance variables for memoization” in the [styleguide](https://github.com/thoughtbot/guides/tree/master/style/rubyhttps://github.com/thoughtbot/guides/tree/master/style/ruby)

Address todos generated by rubocop for files in the lib/generators directory

---

features/generators.feature
lib/generators/factory_bot/model/model_generator.rb

Fixes #305 
When generating factories in the same file (for example
spec/factories.rb), before this PR we didn't put newlines between the
factories. So if you generated a user factory, then a robot factory, you
would end up with something like this:
```rb
FactoryBot.define do
factory :robot do
name { "MyString" }
end
factory :user do
name { "MyString" }
end
end
```
With this PR, generating those factories will now look like:
```rb
FactoryBot.define do
factory :robot do
name { "MyString" }
end
factory :user do
name { "MyString" }
end
end
```
Note that the final newline is not ideal, but it will only be added when
generating the first factory, whereas the missing newline after
factories was happening every time we generated a new factory. So
with this PR we will only need to fix a …

Add newline between factories in same file

---

README.md
features/generators.feature
lib/generators/factory_bot/model/model_generator.rb
lib/generators/factory_bot/model/templates/factories.erb

PR #135 introduced the ability to generate factories in one file, but it
also removed the ability to use custom templates for generating
factories. This PR adds back the ability to use custom templates when
generating factories in separate files. I doubt this was a heavily used
feature, but it has come up a few times and it I think supporting it
simplifies the generator.
Closes #147
Closes #148
Closes #193
PR #193 basically reverted #135, which is undesirable. thoughtbot
projects generally prefer putting all the factories in one file.
Co-authored-by: Nick Sanford <me@nicksanford.io>

Allow using custom template for the generator

---

features/generators.feature
lib/generators/factory_bot/model/model_generator.rb

Closes #231
When generating factories for namespaced models
(like `Admin::User`), we can follow the pattern used by the model and model
test generators of generating the file inside a directory matching the namespace.
With this commit we generate `test/factories/admin/user.rb` instead of
`test/factories/admin_user.rb`.

Generate namespaced factories in a directory

---

.travis.yml

Rails 4.2 requires bundler < 2.0, but on travis we are getting 2.0.1
There is probably a better way to do this so we don't have to update
this every time travis starts using a new version, but I am going to
merge this for now to unblock the release of 5.0.0.rc1

Use an older version of bundler

---

README.md

The correct path use the generator name which isn't pluralized.

Update README section about generator template

---

features/fixture_replacement_config.feature
features/generators.feature
features/load_definitions.feature
features/support/rails_template

Currently, the `sqlite3` in `Gemfile` generated by `rails new` is not compatible with Rails.
To solve this issue, modified it to use compatible `sqlite3` using template.
Ref: https://github.com/rails/rails/issues/35161

Use compatible sqlite3 version in test application

---

lib/factory_bot_rails/definition_file_paths.rb
spec/factory_bot_rails/definition_file_paths_spec.rb

Currently, `factories`, `test/factories` and `spec/factories` are specified by default as reload watching paths.
In many applications, there are directories which do not exist (perhaps do not have` spec` if using minitest and do not have` spec` if using minitest).
In Rails 5 series, if specify a path that does not exist in`EventedFileUpdateChecker`, its parent is added to the watching path.
As a result, `node_modules` is also included in the watching path, and unexpectedly many directories and files are included in listen's watching targets. Also, if symlink is included in `node_modules`, it also causes warning of listen.
This issue is solved in Rails 6. However, since many applications use this gem in Rails 5 and below, it is good not to add directories that do not exist on the gem side. …

Only add exist paths to reloading target

---

features/reloading.feature
features/step_definitions/appraisal.rb

This test captures what I think is going on in
https://github.com/thoughtbot/factory_bot_rails/issues/323
Currently the factory_bot_rails reloader only reloads factory
definitions when the definition files have changes (using
`execute_if_updated`).
This can cause problems when editing an application file without also
editing a factory_bot definition file. Rails will reload the entire
application, but will not reload the definitions. This causes
factory_bot to have references to classes that were unloaded from the
Rails application and replaced with new classes.
https://github.com/thoughtbot/factory_bot_rails/pull/329 replaces
`execute_if_updated` with `execute` so that factory_bot_rails will
reload the definition files whenever anything in the application is
changed. Hopefully that PR …

Write a failing test for reloading with Spring

---

features/load_definitions.feature
lib/factory_bot_rails/railtie.rb

We removed the call to `FactoryBot.load_definitions` in the
`after_initialize` hook in dcfc9f6 because the other changes in that
commit were causing us to sometimes call `FactoryBot.load_definitions`
after `FactoryBot.reload`.
We could have changed `FactoryBot.load_definitions` to
`FactoryBot.reload`, which is what this PR does, but it didn't seem
necessary at the time since all the tests were still passing.
We fixed a problem in 9b83f48 that was causing us to watch the root
directory of the project. This fix caused a test failure, but I ended up
changing the test in 2b7bca0 because it seemed like an unlikely
scenario.
This PR adds back the original test case. Although I do think it
unlikely, I would rather not risk making a breaking change in the next
patch release.

Add back loading definitions in after_initialize

---

README.md

Even if both Rails engine gem and factory_bot_rails gem are written on Gemfile, `defined?(FactoryBotRails)` returns false because it depends on the order on Gemfile.
I'm not sure it should be `+=` or `=` though, anyway, it must be an Array.

Fix definition_file_paths setting for Rails engine

---

.travis.yml
Appraisals
gemfiles/rails5.0.gemfile
gemfiles/rails5.1.gemfile
gemfiles/rails5.2.gemfile

This pull request adds active_storage, action_mailer bootsnap and sass-rails gems to address these errors:
* Address  undefined method `active_storage'
https://travis-ci.org/yahonda/factory_bot_rails/jobs/567544663#L802
```
+/home/travis/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `active_storage' for #<Rails::Application::Configuration:0x000000000417d758> (NoMethodError)
```
* Address undefined_method `action_mailer'
https://travis-ci.org/thoughtbot/factory_bot_rails/jobs/548726224#L1657
```ruby
+/home/travis/.rvm/gems/ruby-2.4.6/gems/railties-5.0.7.2/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `action_mailer' for #<Rails::Application::Configuration:0x0000000002807418> (NoMethodError) …
```

Add active_storage, action_mailer bootsnap and sass-rails gems

---

features/reloading.feature
lib/factory_bot_rails/reloader.rb

Fixes #336
Alternate solution to #343
The initialization process looks like this:
Rails runs all of the initializers
1. Run the ["factory_bot.set_factory_paths"][set_factory_paths]
initializer
2. Run the ["factory_bot.register_reloader"][register_reloader]
initializer, which sets up a [prepare callback][]
3. Run the [`:run_prepare_callbacks`][] initializer
4. This triggers the factory_bot [prepare callback][], which causes
factory\_bot to [reload][]
Rails runs `after_initialize` callbacks
1. [I18n initializes]
2. factory\_bot [reloads again][] as described in #334
The double reloading of factory_bot in this initialization is not ideal,
but also shouldn't generally cause any problems on its own.
The problems people are having in #336 come from the fact that
I18n gets set up in an …

Ensure factory_bot only loads after initialization

---

Appraisals
features/step_definitions/rails_steps.rb
gemfiles/rails5.0.gemfile
gemfiles/rails5.1.gemfile
gemfiles/rails5.2.gemfile
gemfiles/rails6.0.gemfile

Related to point 1 of [this](https://github.com/thoughtbot/factory_bot_rails/issues/370#issuecomment-605666776) comment

Add skip options for test app creation

---

.travis.yml

And drop support for EOL 2.3 (holding off on dropping 2.4 since the
website hasn't yet been updated to show that it is EOL)
https://www.ruby-lang.org/en/downloads/branches/

Test against ruby 2.7

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This commit adds issue templates for bug reports and feature requests,
hopefully making issue triage a bit easier. This was created using
GitHub's [issue template UI].
[issue template UI]: https://github.com/thoughtbot/factory_bot_rails/issues/templates/edit

Add issue templates [skip ci]

---

spec/factory_bot_rails/railtie_spec.rb

We are no longer testing against Rails 4.2, so we no longer need to
branch for the Rails 4.2 style reloader

Remove branch for rails 4.2 reloader

---

features/reloading.feature

Previously our tests were not covering the line where we [add the
factory_bot_rails reloader to the list of Rails reloaders][reloaders
push].
[Spring checks this reloaders list][spring] to decide whether it
needs to reload the rails application. Without adding our reloader to
this list changes to factory_bot definitions would only get picked up
by running `spring stop` (or disabling spring entirely).
This test will ensure we don't accidentally break this interaction
between factory_bot_rails and spring. I verified that this test fails
when deleting the relevant line (no other tests in the suite fail).
While adding this test this commit pulls out a bit of shared background for
the tests in this file, and also removes some Rails 4.2 logic that isn't
necessary anymore since we won't support …

Add missing test coverage for using spring

---

Appraisals
gemfiles/rails6.0.gemfile

This matches a change made in a recent version of Rails 6.0.
Without this commit, CI fails because the wrong version of the gem gets
installed.

Bump listen to ~> 3.2

---

lib/factory_bot_rails/railtie.rb
lib/factory_bot_rails/reloader.rb
spec/factory_bot_rails/reloader_spec.rb

Alternate fix for #336. We went with #347 instead because the solution
in this commit didn't work with Rails 4.2. Since we are no longer
supporting Rails 4.2, I think this is a better approach.
The original problem looked like this:
Rails runs all of the initializers
1. Run the ["factory_bot.set_factory_paths"][set_factory_paths]
initializer
2. Run the ["factory_bot.register_reloader"][register_reloader]
initializer, which sets up a [prepare callback][]
3. Run the [`:run_prepare_callbacks`][] initializer
4. This triggers the factory_bot [prepare callback][], which causes
factory\_bot to [reload][]
Rails runs `after_initialize` callbacks
1. [I18n initializes]
2. factory\_bot [reloads again][] as described in #334
Triggering the first factory_bot reload before initializing I18n could
cause …

Set up reloading after_initialize

---

NEWS.md

It looks like it was omitted by mistake.

Update NEWS.md to mention v5.2.0

---

.standard_todo.yml
lib/factory_bot_rails/generators/null_generator.rb

I looked more into the `RedundantInitialize` cop and it shows splat arguments as acceptable. That seems good enough here—it's not strictly the same arity, but that doesn't really matter for this null object.
I also upgraded all the dev dependencies in https://github.com/thoughtbot/factory_bot_rails/commit/b6463a937da8e6129cbb34d7faa7f0a5b9c71b23 so we get a version of RuboCop that [marks this particular cop as unsafe](https://github.com/rubocop/rubocop/commit/f3b201bf48cfc0249a7676c3461dfd5934ba758d), and a version of standard that [separates autocorrection of safe and unsafe cops](https://github.com/standardrb/standard/pull/545). That should hopefully prevent us from incorrectly fixing unsafe cops in the future.
cc @mathieujobin

Address standard TODO

---

.github/workflows/build.yml

This adds some extra coverage for combinations of newer versions of Ruby and Rails.
A number of the other versions are EOL or soon-to-be EOL, and we'll probably drop them anyway whenever we do another major release of factory_bot_rails, so being thorough there probably doesn't matter as much.

Expand matrix for more recent versions

---

features/fixture_replacement_config.feature

The latest release of Bundler [removed] the "Using " lines from the output unless `--verbose` is passed. Ruby 3 ships with its own Bundler, which still has that line, but Ruby 2.7 does not, so we install the latest on CI. This is causing those tests to fail.
[removed]: https://github.com/rubygems/rubygems/pull/6804

Bundler 2.4.19 removed the "Using " lines

---

Gemfile.lock
README.md
factory_bot_rails.gemspec
lib/factory_bot_rails/factory_validator.rb
lib/factory_bot_rails/factory_validator/active_record_validator.rb
lib/factory_bot_rails/railtie.rb
spec/factory_bot_rails/factory_validator/active_record_validator_spec.rb
spec/spec_helper.rb
spec/support/macros/define_constant.rb

Alternative to [thoughtbot/factory_bot#1586][]
Depends on [thoughtbot/factory_bot#1587][]
First, introduce the `FactoryBotRails::FactoryValidator` class to serve as a generic `factory_bot.compile_factory` event observer.
Throughout the lifecycle of the `FactoryBotRails::Railtie`, afford various initializers with opportunities to add purpose-built validators to the instance's internal set.
When `factory_bot.compile_factory` events are published, iterate through the list of validators and forward along the value of the [event.payload][] to the validator's `#validate!` method.
Next, introduce the Active Record-specific
`FactoryBotRails::FactoryValidator::ActiveRecordValidator` class. Only require the module whenever [Active Record's engine is loaded][on_load].
The …

Reject sequence definitions for Active Record primary keys

---

lib/rails/projections.json

Rails.vim allows gems to provide their own projections compatible with
Dispatch.vim by placing them at lib/rails/projections.json. This
configuration allows:
- :A from a factory to alternate to the test file
- :Efactory (and :{S,V,T}factory) to navigate to or create a new factory
- highlights FactoryBot macros as Ruby macros
- Sets up :{E,S,V,T}unittest for factories => model specs
To use this, you'll need Rails.vim, Bundler.vim, and Dispatch.vim
plugins.
See `:help rails-projections` or [the file on
GitHub](https://github.com/tpope/vim-rails/blob/6bc0c7826d68f8c44c8347a3012aa79ade4f0a22/doc/rails.txt#L611-L726)
for more clarity on what specifically each config key is doing.
Inspired and updated from [@henrik's
Gist](https://gist.github.com/henrik/5676109#file-config-projections-json-L10-L …

Add projections.json for Dispatch.vim support

---

README.md

The default branch is `main` now and we should link to the latest files.

Fix a link to old files

---

.github/workflows/build.yml

Your CI is using a very outdated version of [actions/checkout](https://github.com/actions/checkout) 😄 
With this PR I have bumped that version to the latest stable one - [v4](https://github.com/actions/checkout/releases/tag/v4.0.0)

Bump actions/checkout to latest version

---

factory_bot_rails.gemspec

Rubygems.org does not show the changelog in its UI, because this gem does not follow the expected convention, and is missing the correct config. 
This PR explicitly lists the location of the file `NEWS.md` as the file with the Changelog.
e.g.:
An alternative solution would be to rename `NEWS.md` to `CHANGELOG.md`

adding config to point to the changelog file

---

.standard_todo.yml

The CI is failing due to a few Standard violations. Fixing them is not trivial, so ignoring in the meantime and adding them to a standard-todo list will help us visualize when the CI is actually broken. 
We'll work on fixing the violations in a follow-up PR.

Ignore Standard Style/ArgumentsForwarding violations temporarily

---

Gemfile.lock
NEWS.md
RELEASING.md
factory_bot_rails.gemspec

* Update CI to run Ruby 3.3 by @aberkakis in https://github.com/thoughtbot/factory_bot_rails/pull/464
* Ignore Standard Style/ArgumentsForwarding violations temporarily by @sarahraqueld in https://github.com/thoughtbot/factory_bot_rails/pull/489
* Bump standard from 1.32.1 to 1.40.0 by @dependabot in https://github.com/thoughtbot/factory_bot_rails/pull/487
* Bump rspec-rails from 6.1.0 to 6.1.4 by @dependabot in https://github.com/thoughtbot/factory_bot_rails/pull/490
* Bump factory_bot from 6.4.0 to 6.5.0 by @dependabot in https://github.com/thoughtbot/factory_bot_rails/pull/492
* Bump rake from 13.1.0 to 13.2.1 by @dependabot in https://github.com/thoughtbot/factory_bot_rails/pull/491
* Update Bundler to v2.5.21 by @smaboshe in https://github.com/thoughtbot/factory_bot_rails/pull/499
* …

Release 6.4.4 [ci skip]

---

.github/workflows/build.yml

According to [Ruby lang page](https://www.ruby-lang.org/en/downloads/branches/), Ruby 3.0 reached EOL on April 2024.
Supporting Ruby 3.0 is preventing the project from implementing standardrb most recent version, since we need to add an special case for syntax introduced in 3.2.
See #482 and #474

Drop support for Ruby 3.0

---

factory_bot_rails.gemspec

fixes #456
`required_ruby_version` is an optional property in specification though [recommended by Rubygems guide](https://guides.rubygems.org/specification-reference/). The change requests follows specification of [factory_bot](https://github.com/thoughtbot/factory_bot/blob/main/factory_bot.gemspec#L18).

Add missing required Ruby version to gemspec

---

spec/support/macros/define_constant.rb

Fixes https://github.com/thoughtbot/factory_bot_rails/issues/474
Standard is failing: 
```standard: Use Ruby Standard Style (https://github.com/standardrb/standard)
spec/support/macros/define_constant.rb:10:40: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (&).
spec/support/macros/define_constant.rb:11:52: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (&).
spec/support/macros/define_constant.rb:20:32: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (&).
spec/support/macros/define_constant.rb:25:43: Style/ArgumentsForwarding: Use anonymous block arguments forwarding (&).
```
Running `standardrb --fix` changes `&block` to `&`, however, this only works for ruby >= 3.2.
Since we still support Ruby 3.0, this change introduces …

Fix standardrb violations

---

.github/workflows/build.yml
.standard_todo.yml

Dropping support for Ruby version 3.0 #507 that enables removal of violations of linting #482 the linter should be activated in CI. Workflow follows job from [factory_bot](https://github.com/thoughtbot/factory_bot/blob/main/.github/workflows/build.yml#L54-L65).

Activate linter in CI

---

.github/workflows/build.yml

Commits to a Pull Request branch have been triggering a build twice. That is happening because a `push` to a pull request is both a `push` and a `pull_request` activity.
This commit fixes this issue by limiting the `push` trigger to the `main` branch, ensuring that merged Pull Requests will run linting and tests on the main branch, and that any Pull Request activity will also trigger a build.

Limit `push` builds to the `main` branch

---

Gemfile.lock
factory_bot_rails.gemspec

The olders Rails version that we run on CI is 6.1, but our gemspec runtime dependencies ask for Rails 5.0 or higher.
This commit fixes that, adding Rails 6.1 as the minimum required version. When dropping supported Rails versions, let's ensure that the gemspec file is up-to-date.

Update gemspec with supported Rails version

---

factory_bot_rails.gemspec

It seems that the support of Ruby 3.0 has dropped #507. This PR updates `required_ruby_version` to match it.

Update `required_ruby_version` to require >= Ruby 3.1
